rho central foam issues debug 1

diff --git a/openfoam/combined_test_workflow/Allrun b/openfoam/combined_test_workflow/Allrun
--- a/openfoam/combined_test_workflow/Allrun
+++ b/openfoam/combined_test_workflow/Allrun
@@ -5,10 +5,15 @@ CORES=4
 CONTROL_DICT="system/controlDict"
 BACKUP_DICT="system/controlDict.original"
 
-# File Swapping Config
+# File Swapping Config (Schemes)
 SCHEMES="system/fvSchemes"
 SCHEMES_COMP="system/fvSchemes.compressible"
 SCHEMES_BACKUP="system/fvSchemes.backup"
+
+# File Swapping Config (Options)
+OPTIONS="system/fvOptions"
+OPTIONS_COMP="system/fvOptions.compressible"
+OPTIONS_BACKUP="system/fvOptions.backup"
 
 # Output Directories
 ARCHIVE_DIR="saved_stages"
@@ -29,12 +34,18 @@ cleanup() {
     if [ -f "$BACKUP_DICT" ]; then
         mv $BACKUP_DICT $CONTROL_DICT
     fi
+    
     # Restore original schemes
     if [ -f "$SCHEMES_BACKUP" ]; then
         mv $SCHEMES_BACKUP $SCHEMES
     fi
-    rm -rf processor*
-    # rm -rf postProcessing/forceCoeffs
+
+    # Restore original options
+    if [ -f "$OPTIONS_BACKUP" ]; then
+        mv $OPTIONS_BACKUP $OPTIONS
+    fi
+
+    # rm -rf processor*
     echo "Cleanup complete."
 }
 trap cleanup EXIT
@@ -47,8 +58,15 @@ mkdir -p $FORCES_DIR
 echo "Backing up controlDict..."
 cp $CONTROL_DICT $BACKUP_DICT
 
-# Back up the current (Incompressible) schemes
+# Back up the current (Incompressible) schemes & options
 cp $SCHEMES $SCHEMES_BACKUP
+
+# Back up options if they exist, otherwise creating a dummy backup prevents errors
+if [ -f "$OPTIONS" ]; then
+    cp $OPTIONS $OPTIONS_BACKUP
+else
+    touch $OPTIONS_BACKUP # Marker to delete it later if it didn't exist
+fi
 
 echo "Resetting 0/ folder..."
 rm -rf 0
@@ -58,100 +76,115 @@ cp -r 0.orig 0
 cp 0.orig/U.slip 0/U
 cp 0.orig/p.incompressible 0/p
 
-# --- STEP 1: POTENTIAL FLOW ---
-echo "Decomposing mesh..."
-decomposePar > log.decomposePar
+# # --- STEP 1: POTENTIAL FLOW ---
+# echo "Decomposing mesh..."
+# decomposePar > log.decomposePar
 
-echo "Running potentialFoam (Parallel)..."
-# (Removed -writep to avoid pressure unit crash)
-mpirun -np $CORES potentialFoam -parallel -writep > log.potentialFoam
+# echo "Running potentialFoam (Parallel)..."
+# # (Removed -writep to avoid pressure unit crash)
+# mpirun -np $CORES potentialFoam -parallel -writep > log.potentialFoam
 
-#moving the critical time 0 cases to some arbitrary time (1234)
-echo ">> ARCHIVING: Potential Flow results..."
-for proc in processor*; do
-    cp -r $proc/0 $proc/1234
-done
-#combining all 1234 times together
-reconstructPar -time 1234 > log.reconstructPot
+# # moving the critical time 0 cases to some arbitrary time (1234)
+# echo ">> ARCHIVING: Potential Flow results..."
+# for proc in processor*; do
+#     cp -r $proc/0 $proc/1234
+# done
+# # combining all 1234 times together
+# reconstructPar -time 1234 > log.reconstructPot
 
-# Get the PotentialFoam Force values
-echo ">> ARCHIVING: PotentialFoam Force Coefficients..."
-simpleFoam -postProcess -time 1234 > log.potForces
+# # Get the PotentialFoam Force values
+# echo ">> ARCHIVING: PotentialFoam Force Coefficients..."
+# simpleFoam -postProcess -time 1234 > log.potForces
 
-#copying the post processing outputs from postProcess folder into an archive folder
-if [ -d "postProcessing" ]; then
-    mkdir -p $FORCES_DIR/01_potentialFoam
-    cp -r postProcessing/* $FORCES_DIR/01_potentialFoam/
-    rm -rf postProcessing
-fi
+# # copying the post processing outputs from postProcess folder into an archive folder
+# if [ -d "postProcessing" ]; then
+#     mkdir -p $FORCES_DIR/01_potentialFoam
+#     cp -r postProcessing/* $FORCES_DIR/01_potentialFoam/
+#     rm -rf postProcessing
+# fi
 
-mkdir -p $ARCHIVE_DIR/01_potential
-mv 1234 $ARCHIVE_DIR/01_potential/0
-for proc in processor*; do
-    rm -rf $proc/1234
-done
+# mkdir -p $ARCHIVE_DIR/01_potential
+# mv 1234 $ARCHIVE_DIR/01_potential/0
+# for proc in processor*; do
+#     rm -rf $proc/1234
+# done
 
 
+# # --- STEP 2: SIMPLEFOAM (Steady State) ---
+# echo "Switching to noSlip..."
+# sed -i '/rocket/,/}/ s/type.*slip;/type noSlip;/g' processor*/0/U
 
-# --- STEP 2: SIMPLEFOAM (Steady State) ---
-echo "Switching to noSlip..."
-sed -i '/rocket/,/}/ s/type.*slip;/type noSlip;/g' processor*/0/U
+# echo "Running simpleFoam (Parallel)..."
+# mpirun -np $CORES simpleFoam -parallel > log.simpleFoam
 
-echo "Running simpleFoam (Parallel)..."
-mpirun -np $CORES simpleFoam -parallel > log.simpleFoam
+# echo "Reconstructing simpleFoam results..."
+# reconstructPar -latestTime > log.reconstructSimple
 
-echo "Reconstructing simpleFoam results..."
-reconstructPar -latestTime > log.reconstructSimple
+# # Find result, ignore '0.orig' and '0'
+# simpleResult=$(ls -d [0-9]* | grep -v "orig" | sort -n | tail -n 1)
 
-# Find result, ignore '0.orig' and '0'
-simpleResult=$(ls -d [0-9]* | grep -v "orig" | sort -n | tail -n 1)
+# if [ "$simpleResult" == "0" ] || [ -z "$simpleResult" ]; then
+#     echo "Error: SimpleFoam did not produce a valid time step!"
+#     exit 1
+# fi
 
-if [ "$simpleResult" == "0" ] || [ -z "$simpleResult" ]; then
-    echo "Error: SimpleFoam did not produce a valid time step!"
-    exit 1
-fi
+# echo ">> ARCHIVING: SimpleFoam Field results..."
+# mkdir -p $ARCHIVE_DIR/02_simple_incompressible
+# cp -r $simpleResult/* $ARCHIVE_DIR/02_simple_incompressible/
 
-echo ">> ARCHIVING: SimpleFoam Field results..."
-mkdir -p $ARCHIVE_DIR/02_simple_incompressible
-cp -r $simpleResult/* $ARCHIVE_DIR/02_simple_incompressible/
+# echo ">> ARCHIVING: SimpleFoam Force Coefficients..."
+# if [ -d "postProcessing" ]; then
+#     mkdir -p $FORCES_DIR/02_simpleFoam
+#     cp -r postProcessing/* $FORCES_DIR/02_simpleFoam/
+#     rm -rf postProcessing
+# else
+#     echo "Warning: No postProcessing folder found (Check controlDict functions)."
+# fi
 
-echo ">> ARCHIVING: SimpleFoam Force Coefficients..."
-if [ -d "postProcessing" ]; then
-    mkdir -p $FORCES_DIR/02_simpleFoam
-    cp -r postProcessing/* $FORCES_DIR/02_simpleFoam/
-    rm -rf postProcessing
-else
-    echo "Warning: No postProcessing folder found (Check controlDict functions)."
-fi
+# --- STEP 3: RESET FOR COMPRESSIBLE RUN ---
+echo "Restoring clean Compressible Initial Conditions from 0.orig..."
 
-# --- STEP 3: BRIDGE TO COMPRESSIBLE ---
-echo "Bridging to Compressible Physics..."
-cp $simpleResult/U 0/U
-cp $simpleResult/k 0/k
-cp $simpleResult/omega 0/omega
+# 1. Clear out old results from simpleFoam/potentialFoam to prevent ghost data
+rm -f 0/p 0/T 0/U 0/phi 0/rho
+# Also remove the simpleResult folder if it exists
 rm -rf $simpleResult
 
-# Load Compressible Pressure/Temp
-rm 0/p
+# 2. Copy the "Source of Truth" files (Must exist in 0.orig!)
+#    - p.compressible: 101325 Pa (Absolute)
+#    - T.compressible: 300 K
+#    - U.coldStart:    Internal 0, Inlet -500
 cp 0.orig/p.compressible 0/p
-cp 0.orig/T.orig 0/T
 
-# --- STEP 4: SWAP SCHEMES & RUN RHOCENTRALFOAM ---
+if [ -f "0.orig/T.compressible" ]; then
+    cp 0.orig/T.compressible 0/T
+else
+    echo "Warning: 0.orig/T.compressible not found, using T.orig"
+    cp 0.orig/T.orig 0/T
+fi
+
+cp 0.orig/U.coldStart    0/U
+
+echo ">> Fields reset. Ready for rhoCentralFoam."
+
+# --- STEP 4: SWAP SCHEMES & OPTIONS & RUN RHOCENTRALFOAM ---
 echo "Swapping to Compressible Schemes..."
 cp $SCHEMES_COMP $SCHEMES
+
+echo "Swapping to Compressible fvOptions..."
+cp $OPTIONS_COMP $OPTIONS
 
 echo "Updating controlDict for Supersonic Flow..."
 # Use Adjustable Time Stepping for Speed
 foamDictionary $CONTROL_DICT -entry startFrom -set startTime
 foamDictionary $CONTROL_DICT -entry startTime -set 0
 foamDictionary $CONTROL_DICT -entry endTime -set 0.015
-foamDictionary $CONTROL_DICT -entry writeInterval -set 0.015 #ensures it also writes the last line of needed
+foamDictionary $CONTROL_DICT -entry writeInterval -set 0.015 
 
 # 'adjustableRunTime' forces the solver to hit endTime exactly to trigger a save.
 foamDictionary $CONTROL_DICT -entry writeControl -set adjustableRunTime
 
 foamDictionary $CONTROL_DICT -entry adjustTimeStep -set yes
-foamDictionary $CONTROL_DICT -entry maxCo -set 0.2
+foamDictionary $CONTROL_DICT -entry maxCo -set 0.1
 foamDictionary $CONTROL_DICT -entry deltaT -set 1e-6
 foamDictionary $CONTROL_DICT -entry functions/forces/rho -set rho
 
